package pack;

import org.openqa.selenium.By;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.TimeUnit;

/**
 * Created by Kolja on 25.03.2017.
 */
public class MyWindow extends JFrame {
    private JPanel panel1;
    private JTextArea textArea1;
    private JButton openKlybok;
    private JButton openKlumba;
    private JButton uploadKlumba;
    private JButton uploadKlybok;
    private JComboBox comboBox1;
    private JButton encodeButton;
    private JTextPane textPane1;
    private EncoderKlybok encoderKlybok = Main.encoderKlybok;
    private EncoderKlumba encoderKlumba = Main.encoderKlumba;
    private WebConnect connectKlybok = Main.connectKlubok;
    private WebConnect connectKlymba = Main.connectKlumba;


    //for combobox
    private String[] ageArray = {"<6мес", "6-9мес", "9-12мес", "12-18мес", "18-24мес", "2-3года",
            "3-4года", "4-5год", "5-6год", "6-7год", "7-8год", "8-9год", "9-10год",
            "10-11год", "11-12год", "12-13год"};

    public MyWindow() {

        $$$setupUI$$$();
        setContentPane(panel1);
        setVisible(true);
        setSize(500, 300);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);


        uploadKlybok.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                connectKlybok.setText();
            }
        });




        uploadKlumba.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        openKlybok.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                connectKlybok.connectTo("https://klubok.com/item/new-ad");
            }
        });
        openKlumba.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                connectKlymba.connectTo("https://kloomba.com/new-ad/");
//                connectKlymba.getDriver().findElement(By.xpath(".//*[@id='kl-nav-user']/ul/li[3]/a/span")).click();
//                connectKlymba.getDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
//                connectKlymba.getDriver().findElement(By.xpath(".//*[@id='kl-login-form']/div[3]/input"))
//                                            .sendKeys("****email****");
//                connectKlymba.getDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
//                connectKlymba.getDriver().findElement(By.xpath(".//*[@id='kl-login-form']/div[3]/div[1]/input"))
//                                            .sendKeys("****password****");
//                connectKlymba.getDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
//                connectKlymba.getDriver().findElement(By.xpath(".//*[@id='kl-login-form']/div[3]/button")).click();
//                connectKlymba.getDriver().manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
//                connectKlymba.connectTo("https://kloomba.com/new-ad/");
            }
        });
        comboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JComboBox cb = (JComboBox) e.getSource();
                String choise = (String) cb.getSelectedItem();
                encoderKlybok.setAge(choise);
                encoderKlumba.setAge(choise);
            }
        });
        encodeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                encoderKlybok.encode(textArea1.getText());
                encoderKlumba.encode(textArea1.getText());
                encoderKlybok.setState("by");
                encoderKlumba.setState("by");

                textPane1.setText(encoderKlybok.toString() + '\t' + encoderKlumba.toString());

            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here

        comboBox1 = new JComboBox(ageArray);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 3, new Insets(0, 0, 0, 0), -1, -1));
        textArea1 = new JTextArea();
        panel1.add(textArea1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        openKlybok = new JButton();
        openKlybok.setText("Open Klybok");
        panel1.add(openKlybok, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        openKlumba = new JButton();
        openKlumba.setText("Open Klumba");
        panel1.add(openKlumba, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        uploadKlumba = new JButton();
        uploadKlumba.setText("Upload Klumba");
        panel1.add(uploadKlumba, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        uploadKlybok = new JButton();
        uploadKlybok.setText("Upload Klybok");
        panel1.add(uploadKlybok, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Kolja PROGRAMM");
        panel1.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        panel1.add(comboBox1, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        encodeButton = new JButton();
        encodeButton.setText("Encode");
        panel1.add(encodeButton, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textPane1 = new JTextPane();
        panel1.add(textPane1, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
